# Generated by Django 4.1.7 on 2023-04-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarifas_motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_inicial', models.IntegerField()),
                ('re_matricula', models.IntegerField()),
                ('traspaso', models.IntegerField()),
                ('traspaso_indeter', models.IntegerField()),
                ('radicado_cuenta', models.IntegerField()),
                ('duplicado_placa', models.IntegerField()),
                ('duplicado_lt', models.IntegerField()),
                ('inscripcion_prenda', models.IntegerField()),
                ('levante_prenda', models.IntegerField()),
                ('cambio_color', models.IntegerField()),
                ('cambio_motor', models.IntegerField()),
                ('regrabacion', models.IntegerField()),
                ('cancelacion_lt', models.IntegerField()),
                ('mod_alerta_propi', models.IntegerField()),
                ('mod_alerta_acree', models.IntegerField()),
                ('traslado_cuenta', models.IntegerField()),
                ('inicial_prenda', models.IntegerField()),
                ('traspaso_prenda', models.IntegerField()),
                ('historial', models.IntegerField()),
            ],
        ),
    ]
