# Generated by Django 4.1.7 on 2023-04-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifas_motos',
            name='historial',
        ),
    ]
