# Generated by Django 4.1.7 on 2023-04-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0004_tarifas_motos_descripcion_tarifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifas_motos',
            name='matricula_inicial',
        ),
        migrations.AddField(
            model_name='tarifas_motos',
            name='valor',
            field=models.IntegerField(default='0'),
        ),
    ]
