# Generated by Django 4.1.7 on 2023-04-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0005_remove_tarifas_motos_matricula_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas_motos',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
