# Generated by Django 4.1.7 on 2023-04-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0006_alter_tarifas_motos_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifas_motos',
            name='valor',
        ),
    ]
