# Generated by Django 4.1.7 on 2023-04-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0007_remove_tarifas_motos_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifas_motos',
            name='valor_tarifa',
            field=models.IntegerField(default=0),
        ),
    ]
