# Generated by Django 4.1.7 on 2023-04-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0009_alter_tarifas_motos_descripcion_tarifa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifas_motos',
            options={'ordering': ['descripcion_tarifa'], 'verbose_name': 'tarifas_motos', 'verbose_name_plural': 'Tarifas Motocicletas'},
        ),
        migrations.AddField(
            model_name='tarifas_motos',
            name='año',
            field=models.CharField(default=2022, max_length=100),
        ),
    ]
