# Generated by Django 4.1.7 on 2023-04-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0010_alter_tarifas_motos_options_tarifas_motos_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas_motos',
            name='año',
            field=models.CharField(default='', max_length=100),
        ),
    ]
