# Generated by Django 4.1.7 on 2023-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0012_alter_tarifas_motos_año'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifas_motos',
            options={'verbose_name': 'tarifas_motos', 'verbose_name_plural': 'Tarifas Motocicletas'},
        ),
        migrations.AddField(
            model_name='tarifas_motos',
            name='valor_tarifa_RUNT',
            field=models.IntegerField(default=0, verbose_name='Valor Tarifa RUNT'),
        ),
        migrations.AlterField(
            model_name='tarifas_motos',
            name='año',
            field=models.CharField(blank=True, max_length=100, verbose_name='año tarifa'),
        ),
        migrations.AlterField(
            model_name='tarifas_motos',
            name='descripcion_tarifa',
            field=models.CharField(max_length=100, verbose_name='Descripcion Tarifa'),
        ),
        migrations.AlterField(
            model_name='tarifas_motos',
            name='valor_tarifa',
            field=models.IntegerField(verbose_name='Valor Tarifa TTO'),
        ),
    ]
