# Generated by Django 4.1.7 on 2023-04-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0013_alter_tarifas_motos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifas_motos',
            name='valor_total',
            field=models.IntegerField(blank=True, default=0, verbose_name='Valor Total'),
        ),
    ]
