# Generated by Django 4.1.7 on 2023-04-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0014_tarifas_motos_valor_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifas_motos',
            options={},
        ),
    ]
