# Generated by Django 4.1.7 on 2023-04-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0015_alter_tarifas_motos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifas_motos',
            options={'verbose_name': 'tarifas_motos', 'verbose_name_plural': 'Tarifas Motocicletas'},
        ),
    ]
