# Generated by Django 4.1.7 on 2023-04-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0016_alter_tarifas_motos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas_motos',
            name='valor_tarifa_RUNT',
            field=models.IntegerField(verbose_name='Valor Tarifa RUNT'),
        ),
        migrations.AlterField(
            model_name='tarifas_motos',
            name='valor_total',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='Valor Total'),
        ),
    ]
