# Generated by Django 4.1.7 on 2023-04-15 15:43

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0019_alter_tarifas_motos_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas_motos',
            name='valor_total',
            field=djmoney.models.fields.MoneyField(decimal_places=1, editable=False, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
