# Generated by Django 4.1.7 on 2023-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0021_alter_tarifas_motos_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifas_motos',
            name='valor_total_currency',
        ),
        migrations.AlterField(
            model_name='tarifas_motos',
            name='valor_total',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='Valor Total'),
        ),
    ]
