# Generated by Django 4.1.7 on 2023-04-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0022_remove_tarifas_motos_valor_total_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas_motos',
            name='valor_tarifa_RUNT',
            field=models.IntegerField(blank=True, verbose_name='Valor Tarifa RUNT'),
        ),
    ]
