# Generated by Django 4.1.7 on 2023-04-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0023_alter_tarifas_motos_valor_tarifa_runt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas_motos',
            name='valor_tarifa_RUNT',
            field=models.IntegerField(verbose_name='Valor Tarifa RUNT'),
        ),
    ]
