# Generated by Django 4.1.7 on 2023-04-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0025_tarifas_carro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifas_carro',
            options={'verbose_name': 'tarifas_carro', 'verbose_name_plural': 'Tarifas Carro'},
        ),
    ]
