# Generated by Django 4.1.7 on 2023-04-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0026_alter_tarifas_carro_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='requisitos_tramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'requisitos_tramites',
                'verbose_name_plural': 'Requisitos Tramites',
            },
        ),
    ]
