# Generated by Django 4.1.7 on 2023-04-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0027_requisitos_tramites'),
    ]

    operations = [
        migrations.CreateModel(
            name='inicial_carro_particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_carro', models.CharField(max_length=100, verbose_name='Requisitos')),
            ],
        ),
    ]
