# Generated by Django 4.1.7 on 2023-04-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0028_inicial_carro_particular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inicial_carro_particular',
            options={'verbose_name': 'inicial_carro_particular', 'verbose_name_plural': 'Requisitos Carro Particular'},
        ),
        migrations.AlterField(
            model_name='inicial_carro_particular',
            name='requisitos_carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites'),
        ),
    ]
