# Generated by Django 4.1.7 on 2023-04-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0030_traspaso_carro_particular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitos_tramites',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
    ]
