# Generated by Django 4.1.7 on 2023-04-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0031_alter_requisitos_tramites_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitos_tramites',
            options={'verbose_name': 'requisitos_tramites', 'verbose_name_plural': 'Listado Requisitos Tramites'},
        ),
        migrations.CreateModel(
            name='rematricula_carro_particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'rematricula_carro_particular',
                'verbose_name_plural': 'Re Matricula Carro Particular',
            },
        ),
    ]
