# Generated by Django 4.1.7 on 2023-04-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0032_alter_requisitos_tramites_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inicial_carro_particular',
            options={'verbose_name': 'inicial_carro_particular', 'verbose_name_plural': 'Requisitos Inicial Carro Particular'},
        ),
        migrations.AlterModelOptions(
            name='rematricula_carro_particular',
            options={'verbose_name': 'rematricula_carro_particular', 'verbose_name_plural': 'Requisitos ReMatricula Carro Particular'},
        ),
        migrations.AlterModelOptions(
            name='requisitos_tramites',
            options={'verbose_name': 'requisitos_tramites', 'verbose_name_plural': 'Requisitos Listado Tramites'},
        ),
        migrations.CreateModel(
            name='remate_carro_particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'remate_carro_particular',
                'verbose_name_plural': 'Requisitos Remate Carro Particular',
            },
        ),
    ]
