# Generated by Django 4.1.7 on 2023-04-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0035_alter_traspaso_indeter_carro_particular_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancela_licen_deterio_carro_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'cancela_licen_deterio_carro_part',
                'verbose_name_plural': 'Requisitos Cancelación licencia Deterioro Carro Particular',
            },
        ),
    ]
