# Generated by Django 4.1.7 on 2023-04-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0036_cancela_licen_deterio_carro_part'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cancela_licen_deterio_carro_part',
            new_name='cancela_licen_deterio_carro_particular',
        ),
        migrations.AlterModelOptions(
            name='cancela_licen_deterio_carro_particular',
            options={'verbose_name': 'cancela_licen_deterio_carro_particular', 'verbose_name_plural': 'Requisitos Cancelación licencia Deterioro Carro Particular'},
        ),
        migrations.CreateModel(
            name='Dupli_Licencia_carro_parti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'Dupli_Licencia_carro_parti',
                'verbose_name_plural': 'Requisitos Duplicado Licencia Carro Particular',
            },
        ),
    ]
