# Generated by Django 4.1.7 on 2023-04-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0038_inscrip_levanta_prenda_carro_parti'),
    ]

    operations = [
        migrations.CreateModel(
            name='cambio_color_carro_parti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'cambio_color_carro_parti',
                'verbose_name_plural': 'Requisitos Cambio Color Carro Particular',
            },
        ),
    ]
