# Generated by Django 4.1.7 on 2023-05-03 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0040_transformacion_carro_particular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='inicial_prenda_carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'inicial_prenda_carro',
                'verbose_name_plural': 'Requisitos Inicial Con Prenda Carro Particular',
            },
        ),
    ]
