# Generated by Django 4.1.7 on 2023-06-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0042_traspaso_prenda_carro_parti_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cambio_servicio_parti_publico',
            options={'verbose_name': 'cambio_servicio_parti_publico', 'verbose_name_plural': 'Requisitos Cambio Publico a Particular'},
        ),
        migrations.CreateModel(
            name='inicial_moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'Inicial_Moto',
                'verbose_name_plural': 'Requisitos Inicial Motor',
            },
        ),
    ]
