# Generated by Django 4.1.7 on 2023-06-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0043_alter_cambio_servicio_parti_publico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='inicial_moto_prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'inicial_moto_prenda',
                'verbose_name_plural': 'Requisitos Inicial Motor Con Prenda',
            },
        ),
    ]
