# Generated by Django 4.1.7 on 2023-06-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0046_traspaso_moto_prensa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='traspaso_moto_prensa',
            new_name='traspaso_moto_prenda',
        ),
    ]
