# Generated by Django 4.1.7 on 2023-06-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0047_rename_traspaso_moto_prensa_traspaso_moto_prenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='radicado_moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'radicado_moto',
                'verbose_name_plural': 'Requisitos Radicado Moto',
            },
        ),
    ]
