# Generated by Django 4.1.7 on 2023-06-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0051_duplicado_licencia_moto'),
    ]

    operations = [
        migrations.CreateModel(
            name='inscribe_lev_prenda_moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'inscribe_lev_prenda_moto',
                'verbose_name_plural': 'Requisitos Inscribe Levanta Prenda Moto',
            },
        ),
        migrations.CreateModel(
            name='cambio_color_moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'cambio_color_moto',
                'verbose_name_plural': 'Requisitos Cambio Color Moto',
            },
        ),
    ]
