# Generated by Django 4.1.7 on 2023-06-27 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina', '0057_transformacion_moto_modificar_alerta_prop_moto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='modificar_alerta_acree_moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'modificar_alerta_acree_moto',
                'verbose_name_plural': 'Requisitos Modificar Alerta Acreedor Moto',
            },
        ),
        migrations.CreateModel(
            name='historial_moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'historial_moto',
                'verbose_name_plural': 'Requisitos Historial Moto',
            },
        ),
        migrations.CreateModel(
            name='cancela_licencia_moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitos_moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pagina.requisitos_tramites')),
            ],
            options={
                'verbose_name': 'cancela_licencia_moto',
                'verbose_name_plural': 'Requisitos Cancelacion Licencia Moto',
            },
        ),
    ]
